basePath: /
definitions:
  request.Request:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  response.Response:
    properties:
      message:
        type: string
    type: object
host: 3.84.60.208
info:
  contact: {}
  description: |-
    RESTful API for user authentication in the GlobalTune E-Commerce platform.
    This API provides secure login functionality using JWT tokens and the Gin framework.
  title: Login Service API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Validates user credentials and returns a JWT token in a cookie
        upon successful authentication.
      parameters:
      - description: User login credentials
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/request.Request'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/response.Response'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Could not generate token
          schema:
            $ref: '#/definitions/response.Response'
      summary: Authenticate user and issue a JWT token
      tags:
      - Authentication
swagger: "2.0"
