basePath: /
definitions:
  model.Order:
    properties:
      id:
        type: string
      items:
        $ref: '#/definitions/model.OrderItems'
    type: object
  model.OrderItems:
    properties:
      billing_details_id:
        type: string
      date:
        type: string
      invoice_id:
        type: string
      number:
        type: integer
      payment_id:
        type: string
      shipping_details_id:
        type: string
    type: object
  request.Request:
    properties:
      data:
        properties:
          billing_details_id:
            type: string
          date:
            type: string
          invoice_id:
            type: string
          payment_id:
            type: string
          shipping_details_id:
            type: string
        type: object
    type: object
  response.Response:
    properties:
      data:
        $ref: '#/definitions/response.ResponseData'
      message:
        type: string
    type: object
  response.ResponseData:
    properties:
      order:
        $ref: '#/definitions/model.Order'
    type: object
host: localhost:80
info:
  contact: {}
  description: |-
    RESTful API to handle the creation of customer orders in the GlobalTune E-Commerce platform.
    This API create orders securely using JWT tokens and the Gin framework.
  title: Create Order Service API
  version: "1.0"
paths:
  /create:
    post:
      consumes:
      - application/json
      description: This endpoint allows authenticated users to create an order by
        providing billing, shipping, and payment details.
      parameters:
      - description: Order Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.Request'
      produces:
      - application/json
      responses:
        "200":
          description: Order created successfully
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/response.Response'
        "401":
          description: Unauthorized or missing token
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: Create a new order
      tags:
      - orders
swagger: "2.0"
