services:
  shipping_details-db:
    image: "mates182/shipping-details-db:latest"
    container_name: shipping_details-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    networks:
      - app-network

  create_shipping_details:
    image: "mates182/create-shipping-details:latest"
    container_name: create_shipping_details
    ports:
      - "80:80"
    environment:
      GIN_MODE: release
      shipping_details_URI: "${shipping_details_URI}"
      shipping_details_BROKER: "${shipping_details_BROKER}"
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - shipping_details-db

networks:
  app-network:
    driver: bridge
