name: Push frontend Services to Docker Hub

on:
  push:
    branches:
      - qa-aws-deploy
    paths:
      - 'FrontEnd/**'
      - '.github/workflows/frontend-dockerhub.yml'

jobs:
  push_to_registry:
    name: Push Docker Images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Frontend Image
      - name: Build and push Frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./FrontEnd/global-tune
          file: ./FrontEnd/global-tune/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/gt-frontend:latest