name: Push Products Services to Docker Hub

on:
  push:
    branches:
      - qa-aws-deploy
    paths:
      - 'BackEnd/Domains/Products/**'
      - '.github/workflows/products-dockerhub.yml'

jobs:
  push_to_registry:
    name: Push Docker Images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Products Database Image
      - name: Build and push Products DB image
        uses: docker/build-push-action@v4
        with:
          context: ./BackEnd/DataBases/products
          file: ./BackEnd/DataBases/products/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/products-db:latest

      # Create Products Image
      - name: Build and push Create Products image
        uses: docker/build-push-action@v4
        with:
          context: ./BackEnd/Domains/Products/create_product
          file: ./BackEnd/Domains/Products/create_product/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/create-product:latest

      # Delete Products Image
      - name: Build and push Delete Products image
        uses: docker/build-push-action@v4
        with:
          context: ./BackEnd/Domains/Products/delete_product
          file: ./BackEnd/Domains/Products/delete_product/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/delete-product:latest

      # Get Products By ID Image
      - name: Build and push Get Products By ID image
        uses: docker/build-push-action@v4
        with:
          context: ./BackEnd/Domains/Products/GetProductById
          file: ./BackEnd/Domains/Products/GetProductById/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/get-product-by-id:latest

      # List Products Image
      - name: Build and push List Products image
        uses: docker/build-push-action@v4
        with:
          context: ./BackEnd/Domains/Products/GetAllProducts
          file: ./BackEnd/Domains/Products/GetAllProducts/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/list-products:latest

      # Products Replicant Image
      - name: Build and push Products Replicant image
        uses: docker/build-push-action@v4
        with:
          context: ./BackEnd/Domains/Products/product_replicant
          file: ./BackEnd/Domains/Products/product_replicant/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/product-replicant:latest

      # Update Products Image
      - name: Build and push Update Products image
        uses: docker/build-push-action@v4
        with:
          context: ./BackEnd/Domains/Products/update_product
          file: ./BackEnd/Domains/Products/update_product/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/update-product:latest

      # Upload image to S3 Service Image
      - name: Build and push Upload image to S3 Service image
        uses: docker/build-push-action@v4
        with:
          context: ./BackEnd/Domains/Products/upload_image_s3
          file: ./BackEnd/Domains/Products/upload_image_s3/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/upload-image-s3:latest

