name: Deploy MongoDB service

on:
  push:
    branches:
      - test
jobs:
  push_to_registry:
    name: Push Docker Images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Products GraphQL Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./BackEnd/DataBases/products/
          file: ./BackEnd/DataBases/products/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/products-db-service-test:latest

      - name: Executing remote ssh on EC2 server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS_SERVER_PDB_TEST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker stop products-db-service-test || echo "No existing process found"
            sudo docker rm products-db-service-test || echo "No existing process found"
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/products-db-service-test:latest
            sudo docker run -d -p 27017:27017 --name products-db-service-test \
              -e MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_ROOT_USERNAME }} \
              -e MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_ROOT_PASSWORD }} \
              ${{ secrets.DOCKER_USERNAME }}/products-db-service-test
